config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "games#index"

  resources :games, except: [:edit, :update, :destroy] do
    get 'search', on: :collection, constraints: { format: 'js' }
    # GET /games/search, meant to only be used with AJAX
  end

  resources :genres, except: [:new, :edit, :create, :update, :destroy]
  resources :platforms, except: [:new, :edit, :create, :update, :destroy]
  resources :platform_families, except: [:new, :edit, :create, :update, :destroy]

  get 'import/igdb'
  get 'import/psn'

  namespace :api do
    namespace :v1 do
      get 'igdb/search'
      post 'igdb/import'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
# Model responsible for handling Genre records
# id: integer
# name: string
# igdb_id: integer
class Genre < ApplicationRecord
  has_and_belongs_to_many :games

  validates :name, presence: true
  validates :igdb_id, presence: true, numericality: { only_integer: true }, uniqueness: true
end

app/controllers/genres_controller.rb
# Controller responsible for handling Genre actions
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.where(id: params[:id]).first

    redirect_to(genres_path) if @genre.nil?
  end
end

app/helpers/genres_helper.rb
# Helper for Genres
module GenresHelper
end

app/views/genres/index.html.erb
<div>
  <h2>Genres</h2>

  <table>
    <tr>
      <th></th>
      <th>Name</th>
    </tr>
    <% @genres.each do |genre| %>
    <tr>
      <td><%= genre.id %></td>
      <td><%= link_to(genre.name, genre_path(genre), action: 'show', class: 'nav-link') %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/genres/show.html.erb
<% content_for(:title) { @genre.name } %>

<div class="genres show">
  <h2>Show Genre</h2>

  <table summary="Genre detail view">
    <tr>
      <th>Name</th>
      <td><%= @genre.name %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @genre.created_at.to_formatted_s(:db) %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @genre.updated_at.to_formatted_s(:db) %></td>
    </tr>
  </table>
  <table class="listing" summary="Game list">
    <tr class="header">
      <th></th>
      <th>Game</th>
    </tr>
    <% @genre.games.each do |game| %>
      <tr>
        <td><%= game.id %></td>
        <td><%= link_to(game.name, game_path(game), :class => 'action show') %></td>
      </tr>
    <% end %>
  </table>
</div>