config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "games#index"

  resources :games, except: [:edit, :update, :destroy] do
    get 'search', on: :collection, constraints: { format: 'js' }
    # GET /games/search, meant to only be used with AJAX
  end

  resources :genres, except: [:new, :edit, :create, :update, :destroy]
  resources :platforms, except: [:new, :edit, :create, :update, :destroy]
  resources :platform_families, except: [:new, :edit, :create, :update, :destroy]

  get 'import/igdb'
  get 'import/psn'

  namespace :api do
    namespace :v1 do
      get 'igdb/search'
      post 'igdb/import'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/controllers/platforms_controller.rb
# Controller responsible for handling Platform actions
class PlatformsController < ApplicationController
  def index
    @platforms = Platform.all
  end

  def show
    @platform = Platform.where(id: params[:id]).first

    redirect_to(platforms_path) if @platform.nil?
  end
end

app/helpers/platforms_helper.rb
# Helper for Platforms
module PlatformsHelper
end

app/views/platforms/index.html.erb
<div>
  <h2>Platforms</h2>

  <table>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Abbreviation</th>
      <th>Family</th>
    </tr>
    <% @platforms.each do |platform| %>
    <tr>
      <td><%= platform.id %></td>
      <td><%= link_to(platform.name, platform_path(platform), action: 'show', class: 'nav-link') %></td>
      <td><%= platform.abbreviation %></td>
      <% if platform.platform_family.present? %>
        <td><%= link_to(platform.platform_family.name, platform_family_path(platform.platform_family), action: 'show', class: 'nav-link') %></td>
      <% else %>
        <td></td>
      <% end %>
    </tr>
    <% end %>
  </table>
</div>

app/views/platforms/show.html.erb
<% content_for(:title) { @platform.name } %>

<div class="platforms show">
  <h2>Show Platform</h2>

  <table summary="Platform detail view">
    <tr>
      <th>Name</th>
      <td><%= @platform.name %></td>
    </tr>
    <tr>
      <th>Family</th>
      <td><%= @platform.platform_family.name %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @platform.created_at.to_formatted_s(:db) %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @platform.updated_at.to_formatted_s(:db) %></td>
    </tr>
  </table>
</div>