config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "games#index"

  resources :games, except: [:edit, :update, :destroy] do
    get 'search', on: :collection, constraints: { format: 'js' }
    # GET /games/search, meant to only be used with AJAX
  end

  resources :genres, except: [:new, :edit, :create, :update, :destroy]
  resources :platforms, except: [:new, :edit, :create, :update, :destroy]
  resources :platform_families, except: [:new, :edit, :create, :update, :destroy]

  get 'import/igdb'
  get 'import/psn'

  namespace :api do
    namespace :v1 do
      get 'igdb/search'
      post 'igdb/import'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/game.rb
# Model responsible for handling Game records
# id: integer
# name: string
# igdb_id: integer
# how_long_to_beat_id: integer
class Game < ApplicationRecord
  has_and_belongs_to_many :genres
  has_and_belongs_to_many :platforms
  has_many :releases, dependent: :destroy

  validates :name, presence: true
  validates :igdb_id, presence: true, numericality: { only_integer: true }, uniqueness: true
  validates :how_long_to_beat_id, numericality: { only_integer: true }, uniqueness: true, allow_nil: true
end

app/controllers/games_controller.rb
# Controller to handle requests that want to view, import or other actions related to Games
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.where(id: params[:id]).first

    redirect_to(games_path) if @game.nil?
  end

  def new
    @games = Import::IGDB::Games.search(params[:search])
  end

  def create
    game = Import::IGDB::Games.import_by_id(params[:igdb_id])
    if game.present?
      redirect_to(game_path(game))
    end
  end
end

app/helpers/games_helper.rb
# Helper for Games
module GamesHelper
end

app/views/games/index.html.erb
<div>
  <h2>Games</h2>

  <table>
    <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Platforms</th>
      </tr>
    </thead>
    <tbody>
      <% @games.each do |game| %>
        <tr>
          <td><%= game.id %></td>
          <td><%= link_to(game.name, game_path(game), action: 'show', class: 'nav-link') %></td>
          <td><%= game.platforms.map { |p| p.name }.join(',') %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/games/new.html.erb
<% content_for(:title) { "New Game" } %>

<div class="games new">
  <h2>Import Game</h2>
  <%= form_tag(new_game_path, method: :get) do %>
    <%= text_field_tag(:search, params[:search]) %>
    <%= submit_tag("Search", class: "btn btn-primary") %>
  <% end %>

  <table class="paddingBetweenCols" summary="Game list">
    <tr class="header">
      <th></th>
      <th>Name</th>
      <th>Platforms</th>
      <th>Genres</th>
    </tr>
    <% @games&.each do |game| %>
      <%= tag.tr(name: game.name) do %>
        <td><%= button_to "Import", { action: "create" }, params: { igdb_id: game.id }, id: game.name %></td>
        <td><%= game.name %></td>
        <td><%= game.platforms&.map{ |platform| platform.name }&.join(", ")&.html_safe %></td>
        <td><%= game.genres&.map{ |genre| genre.name }&.join(", ")&.html_safe %></td>
      <% end %>
    <% end %>
  </table>
</div>

app/views/games/show.html.erb
<% content_for(:title) { @game.name } %>

<div class="games show">
  <h2>Show Game</h2>

  <table summary="Game detail view">
    <tr>
      <th>Name</th>
      <td><%= @game.name %></td>
    </tr>
    <tr>
      <th>Genres</th>
      <td><%= @game.genres.map{ |genre| link_to(genre.name, genre_path(genre), :class => 'action show') }.join(", ").html_safe %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @game.created_at.to_formatted_s(:db) %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @game.updated_at.to_formatted_s(:db) %></td>
    </tr>
  </table>
</div>